manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: ftc
      url-base: https://github.com/ftc
  projects:
    - name: zmk
      remote: refil
      revision: rotrlayer
      import: app/west.yml
    - name: zmk
      remote: ftc
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
